### ISSUE TITLE
Typo - 'Maintainded' should be 'Maintained' at page footer 

### ISSUE THREAD

**Issue by gkrishnan724** [Chirath02/fosswebsite#52]
Sorry, couldn't help but notice this :stuck_out_tongue: 
![typo](https://user-images.githubusercontent.com/21004514/27550565-cfb9dd6a-5abd-11e7-9ca3-f496da7aa007.png)

**Comment by Chirath02** [comment]
Good one :-) Maybe you could share a url where this typo is at?

**Comment by gkrishnan724** [comment]
It's in the footer of the starting page

**Comment by Chirath02** [comment]
Yea got it, thanks. I was looking at the wrong page.
