### ISSUE TITLE
Suggestion - Change the '>' button to `Join Us` in the carousel page

### ISSUE THREAD

**Issue by gkrishnan724** [Chirath02/fosswebsite#53]
The `>` button seems kind of pointless since It is just moving to the next slide.  Also, the `click here` doesn't seem like a hyperlink. 

So I suggest why not replace that `>` to a `Join us` button?

sth like:
![join](https://user-images.githubusercontent.com/21004514/27551322-8f867214-5ac0-11e7-9b44-41b11e76b651.png)

**Comment by Chirath02** [comment]
Maybe it's better to keep it this way as we want people to see the next few slides, rather than skipping to the end.
