### ISSUE TITLE
Login cover page

### ISSUE THREAD

**Issue by gkrishnan724** [Chirath02/fosswebsite#54]
The login page looks too simple, I think we should have a cover page for it. Preferably a group photo or something :)

Also, a link to  `sign up` in the card itself. It took me some time to figure out where the `sign up` button is :stuck_out_tongue:

**Comment by Chirath02** [comment]
I guess it's better to keep pages simple. Will try to add some textured background instead of the pics. 
Yea the sign up button will be fixed.
