### ISSUE TITLE
Improve the project app

### ISSUE THREAD

**Issue by Sparker0i** [Chirath02/fosswebsite#57]
I believe there must be an ability to add other achievements (related to open source) - like developed an open source mobile application, worked on an open source AR/VR related project etc.

**Comment by Chirath02** [comment]
Maybe you could give example data, how it should be named and what all fields you would need?
ex: space to add more pics?
we can add a feature for that.

**Comment by Sparker0i** [comment]
But moving this to projects; would'nt this mean projects of the Foss club, rather than individual open source contributions?

**Comment by Chirath02** [comment]
Nope not really, maybe we can add the project link to the contributions.
