### ISSUE TITLE
Unable to locate conffiles/local-settings.py

### ISSUE THREAD

**Issue by Sparker0i** [Chirath02/fosswebsite#60]
In the INSTALL.md file, I have followed all the instructions in the same order up to the install requirements header.

In the Local settings header, it says to _Copy the local-settings.py from conffiles to fossWebsite directory_
`cp conffiles/local-settings.py fossWebsite/local_settings.py`

Despite following the same order I am unable to locate the conffiles folder, either in my home directory or the website local repo. Am I going wrong anywhere?

**Comment by Chirath02** [comment]
No you don't need that now, it is for production, continue with the other steps.
